id: d6ecb2b1f3bf4584bc4c70550864587a
initial_creation_type: ocr
source_metadata:
  volumes:
    ba935936a42e4e46a5a0a0b3fae26e49:
      base_file: v011.txt
      image_group_id: I1PD95856
      title: ''
      total_pages: 2107
      volume_number: 11
